
FROM maven:3.8.6-openjdk-18 AS build
COPY natflix-backend /usr/src/app/
RUN mvn -f /usr/src/app/natflix-backend/pom.xml clean package -DskipTests=true

FROM openjdk:18-alpine
COPY --from=build /usr/src/app/natflix-backend/target/natflix-backend-0.0.1.jar /usr/src/app/natflix-backend/natflix-backend-0.0.1.jar
#EXPOSE 8080
ENTRYPOINT ["java","-jar", "/usr/src/app/natflix-backend/natflix-backend-0.0.1.jar"]