# Create image based on the official Node 17 image from dockerhub
FROM node:latest

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Get all the code needed to run the app
COPY natflix-frontend /usr/src/app/src

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app/natflix-frontend

# Install dependecies
RUN npm install 

# Expose the port the app runs in
EXPOSE 3000

# Serve the app
CMD npm run start